name: Node CI

on: push
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm run coverage
      env:
        CI: true
    - name: upload coverage
      uses: codecov/codecov-action@v1
      with: 
        token: ${{ secrets.CODECOV_TOKEN }}

on:   
  create:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      
      - name: npm test
        run: |
          npm ci 
          npm test
        env:
          CI: true

      - name: npm auth
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

      - name: publish
        run: npm run build && npm publish --access public --tag latest
